### ISSUE TITLE
Update Import-Section of Readme

### ISSUE THREAD

**Issue by TBARK01** [catppuccin/alacritty#44]
The Import-Section of the Readme.md should correspondent to the [Alacritty-Documentation](https://alacritty.org/releases/0.15.1/config-alacritty.html)
   
```toml
    [general]
   import = [
      # uncomment the flavour you want below:
      "~/.config/alacritty/catppuccin-latte.toml"
      # "~/.config/alacritty/catppuccin-frappe.toml"
      # "~/.config/alacritty/catppuccin-macchiato.toml"
      # "~/.config/alacritty/catppuccin-mocha.toml"
    ]
    ```
